theme: jekyll-theme-minimal
title: Rohit Satija, PhD
tagline: I am an academic researcher and a data scientist based in Berkeley, CA. 
description: My current research interests include the behavior and dynamics of single molecules, particularly protein folding. In the past, I have contributed to the fields of molecular and synthetic biology.
