theme: jekyll-theme-minimal
title: Rohit Satija, PhD
description: I am an academic researcher and a data scientist based in Berkeley, CA. 
My current research interests include the behavior and dynamics of single molecules, particularly protein folding.
In the past, I have contributed to the fields of molecular and synthetic biology. See my Google Scholar profile for a list of publications.
